console.log('Loading API configuration...');
window.REACT_APP_OPENAI_API_KEY = atob('c2stcHJvai13R0pmOXJ6WnJKUTN5SHRRVUR6X1VWZTVyazJqWWEweG1zOHB5eUpfY1lNN0t0V3NF
MzlEWjB3LV90SWU2OTdMZFlTaGZnNXhTWlQzQmxia0ZKSENjMVp4c3ZpVnlIR3N6aVFuemxYMlN1
ZFN0QUhma3I3cXRJS1FVYlBRb054V0V2NGFZclFOUWgxYlFPdldqeS1vZFVKUDl4Z0E=');
console.log('API key loaded:', !!window.REACT_APP_OPENAI_API_KEY);
